
name: CI
 
on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: generate the report
        run: ./gradlew testDebugUnitTestCoverage
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          files: app/build/reports/**/*.xml
      - name: build the app
        run: ./gradlew assembleDebug

      
