
name: CI
 
on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: run the tests
        run: ./gradlew testDebugUnitTest
      - name: build the app
        run: ./gradlew assembleDebug

      
